spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2021322
    url: jdbc:mysql://localhost:3306/signsql
#    将数据库账户密码替换自己的
#    数据库文件放在 src/main/resources 目录下

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
